version: "2"

services:
  tor:
     image: goldy/tor-hidden-service:latest
     links:
          - wordpress
     restart: always
# Keep keys in volumes
     volumes:
          - tor-keys:/var/lib/tor/hidden_service/
     environment:
        # Set mapping ports
         WORLD_TOR_SERVICE_HOSTS: 80:unix://var/run/nginx.sock
  db:
     image: mariadb
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: rootpass
         MYSQL_DATABASE: wordpress
         MYSQL_USER: wordpress
         MYSQL_PASSWORD: wordpress123

  wordpress:
     depends_on:
          - db
     image: wordpress:latest
     links:
          - db
     restart: always
     environment:
         WORDPRESS_DB_HOST: db:3306
         WORDPRESS_DB_USER: wordpress
         WORDPRESS_DB_PASSWORD: wordpress123

             # You can disable network to increase security
    network_mode: none
    command: |
        sh -c 'php-fpm -d variables_order="EGPCS" &&
        sed -i "s|80|unix:/var/run/nginx.sock|" /etc/nginx/nginx.conf &&
        exec nginx -g "daemon off;"'
    volumes:
        - /var/run

volumes:
    tor-keys:
        driver: local
